name: 1.0.$(BuildID)-${{ parameters.service }}-${{ parameters.resource }}

trigger: none

parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: service
    displayName: Select service that needs to be deployed
    type: string
    values:
      - ffc-demo-web
      - ffc-demo-payment-web
    default: ffc-demo-web
  - name: resource
    displayName: Resource Type to deploy
    type: string
    values:
      - application-endpoint
    default: application-endpoint

extends:
  template: template/${{ parameters.resource }}.yaml
  parameters:
    deployFromFeature: ${{ parameters.deployFromFeature }}
    program: ffc
    service: ${{ parameters.service }}
