name: 1.0.$(BuildID)-${{ parameters.service }}-${{ parameters.resource }}

trigger: none

parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: useCustomEnvironments
    displayName: "Select to deploy to custom environments"
    type: boolean
    default: false
  - name: service
    displayName: Select service that needs to be deployed
    type: string
    values:
      - ffc-demo-web
      - ffc-demo-payment-web
    default: ffc-demo-web
  - name: resource
    displayName: Resource Type to deploy
    type: string
    values:
      - application-domain
    default: application-domain

extends:
  template: templates/generic.yaml
  parameters:
    deployFromFeature: ${{ parameters.deployFromFeature }}
    rtlOrCustom: ${{ parameters.rtlOrCustom }}
    program: ffc
    service: ${{ parameters.service }}
    resource: ${{ parameters.resource }}
