parameters:
  - name: deployFromFeature
    type: boolean
    default: false

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA-ADP
      type: github
      ref: refs/tags/1.0.0-latest

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}
    includePlatformEnvs: false
    variableFiles: 
      - /pipelines/vars/common.yaml@_self
      - /pipelines/vars/env/{environment}.yaml@_self
      - /infra/services/eutd/external-services/env-vars/{environment}.yaml@self
    groupedDeployments:
      - name: servicebus_access
        deployments:
          - name: Grant Access to ServiceBus Queues and Topics
            type: 'script'
            scriptType: AzurePowerShell
            path: "infra/scripts/Set-ServiceBus-Entities-RBAC.ps1"
            scriptArguments: >
              -ServiceBusAccessTo '$(serviceBusAccess)'
              -ServiceBusNamespace '$(infraResourceNamePrefix)$(nc_resource_servicebus)$(nc_instance_regionid)01'
              -ServiceBusRgName '$(servicesResourceGroup)'