name: 1.0.$(BuildID)-${{ parameters.service }}-${{ parameters.resource }}

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/services/coreai/*
  drafts: false

trigger: none

parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: useCustomEnvironments
    displayName: "Use Custom Environments"
    type: boolean
    default: false
  - name: service
    displayName: Select service that needs to be deployed
    type: string
    values:
      - mcu-techspike-ai-web
      - core-ai-techradar
      - coreai-mcu-frontend
      - coreai-mcu-generation-oai
      - coreai-mcu-knowledge-pgv
    default: mcu-techspike-ai-web
  - name: ingressType
    displayName: Select ingress type of the service
    type: string
    values:
      - internal
      - external    
    default: internal
  - name: resource
    displayName: Resource Type to deploy
    type: string
    values:
      - application-domain
      - application-registration
      - service-mi-rbac
    default: application-domain

extends:
  template: /.azuredevops/templates/generic-template.yaml
  parameters:
    deployFromFeature: ${{ parameters.deployFromFeature }}
    useCustomEnvironments: ${{ parameters.useCustomEnvironments }}
    program: coreai
    service: ${{ parameters.service }}
    ingressType: ${{ parameters.ingressType }}
    resource: ${{ parameters.resource }}
