parameters:
  - name: deployFromFeature
    type: boolean
    default: false
  - name: program
    type: string
  - name: service
    type: string
  - name: resource
    type: string

extends:
  template: /.azuredevops/templates/services-infra-template.yaml
  parameters:
    environments:        
      - name: 'snd3'
        serviceConnection: AZD-ADP-SND3
        deploymentBranches:
          - 'refs/heads/main'
        developmentEnvironment: true
        privateAgentName: 'DEFRA-ADP-SND3-ubuntu2204'
        azureRegions:
          primary: 'UKSouth'      
      
    deployFromFeature: ${{ parameters.deployFromFeature }}
    program: ${{ parameters.program }}
    service: ${{ parameters.service }}
    resource: ${{ parameters.resource }}